version: "3.8"

services:

  redis-server:
    container_name: redis-server
    image: redis:alpine
    command:
      - "-- requirepass ${REDIS_PASSWORD}"
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./deployment/volumes/redis:/data
